export default [
  {
    id: 1,
    url: "ankui.jpg",
    text: "buy",
    text1: "ankui",
    Remove: "remove",
    value: 1,
  },
  {
    id: 2,
    url: "Spanis.jpg",
    text: "buy",
    text1: "panis-rice.jpg",
    Remove: "remove",
    value: 1,
  },
  {
    id: 3,
    url: "sol.jpg",
    text: "buy",
    text1: "ekwan",
    Remove: "remove",
    value: 1,
  },
  {
    id: 4,
    url: "KWACOCO.jpg",
    text: "buy",
    text1: "Kwacoco",
    Remove: "remove",
    value: 1,
  },
  {
    id: 5,
    url: "rice.jpg",
    text: "buy",
    text1: "jelouf-rice",
    Remove: "remove",
    value: 1,
  },
  {
    id: 6,
    url: "Groundnut-soup-rice.jpg",
    text: "buy",
    text1: "Groundnut-soup-rice",
    Remove: "remove",
    value: 1,
  },
  {
    id: 7,
    url: "red-bean.jpg",
    text: "buy",
    text1: "Rice and Bean",
    Remove: "remove",
    value: 1,
  },
  {
    id: 8,
    url: "cornchap.jpg",
    text: "buy",
    text1: "cornchap.jpg",
    Remove: "remove",
    value: 1,
  },
  {
    id: 9,
    url: "image.jpeg",
    text: "buy",
    text1: "ndole-planatain",
    Remove: "remove",
    value: 1,
  },
  {
    id: 10,
    url: "tun-bana.jpg",
    text: "buy",
    text1: "turning-banana",
    Remove: "remove",
    value: 1,
  },
  {
    id: 11,
    url: "vegan-bean-rice.jpg",
    text: "buy",
    text1: "Vegan-bean-rice",
    Remove: "remove",
    value: 1,
  },
  {
    id: 12,
    url: "fufu-eru.jpg",
    text: "buy",
    text1: "fufu and eru",
    Remove: "remove",
    value: 1,
  },
  // {
  //     id:13,
  //     url:"Simply-Recipes-Jollof.jpg",
  //     text:"buy",
  //       text1:"Recipes fo Jollof"
  // }
];
